"""empty message

Revision ID: 40c7a7a9a621
Revises: 6c89263c0411
Create Date: 2024-03-12 15:13:15.203681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c7a7a9a621'
down_revision = '6c89263c0411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_community', ['community_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_community', type_='unique')

    # ### end Alembic commands ###
